### ISSUE TITLE
Navbar Presists on Every Page

### ISSUE THREAD

**Issue by Will-Babbitt** [Gearhounds/gearhounds.github.io#13]
The Navbar needs to be generalized and included at the top of every page.

This should be included in the templates made in #4

**Comment by Dingle-Bingle** [comment]
Is this not already completed?
![image](https://github.com/Gearhounds/gearhounds.github.io/assets/151408929/04e5a424-c667-49e5-be42-7a820fbb92ec)
![image](https://github.com/Gearhounds/gearhounds.github.io/assets/151408929/1f7a9750-d8c7-46ab-918a-f59221ef4b96)
